### ISSUE TITLE
Discussion of failed travis build for PR #1 for perl version 5.22

### ISSUE THREAD

**Issue by hakonhagland** [jandrew/p5-spreadsheet-reader-format#2]
I investigated the [failed builds](https://travis-ci.org/github/jandrew/p5-spreadsheet-reader-format) for PR #1 a little more. It seems it is related to the version of [DateTime](https://metacpan.org/pod/DateTime) that is used. For some reason the build for 5.22 uses DateTime version 1.44 whereas the other builds uses a higher version.

The difference in version 1.44 (compared to the higher versions) that is relevant to the failed tests is in the pattern function for the `S` pattern, see [line 1297](https://metacpan.org/source/DROLSKY/DateTime-1.44/lib/DateTime.pm#L1297) and compare to the same function in e.g. version 1.51, here [line 1327](https://metacpan.org/source/DROLSKY/DateTime-1.51/lib/DateTime.pm#L1327).

**Comment by jandrew** [comment]
Excellent work by the way and thank you for the contribution

**Comment by jandrew** [comment]
FIx verified
